services:
  - type: web
    name: headshot-generator
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # Free tier - upgrade to standard for production
    region: oregon  # Change to your preferred region (oregon, frankfurt, singapore)
    branch: main
    numInstances: 1
    
    # Environment variables
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "10000"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "false"
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: "10"  # 10MB max upload size
      - key: STREAMLIT_SERVER_MAX_MESSAGE_SIZE
        value: "10"  # 10MB max message size
    
    # Health check configuration
    healthCheckPath: /_stcore/health
    
    # Auto-deploy on git push
    autoDeploy: true
    
    # Build command (if needed)
    # buildCommand: echo "Using Dockerfile for build"
    
    # Start command (defined in Dockerfile)
    # startCommand: streamlit run headshot_app.py --server.port=10000 --server.address=0.0.0.0
    
    # Resource allocation (for paid plans)
    # disk:
    #   name: headshot-storage
    #   mountPath: /app/logs
    #   sizeGB: 1