[server]
# Server configuration for local development
headless = false
port = 8501
address = "localhost"
maxUploadSize = 200  # 200MB max upload size for headshots
maxMessageSize = 200  # 200MB max message size
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration for better UX
primaryColor = "#FF6B35"  # About.me orange for primary actions
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Client configuration
toolbarMode = "minimal"

[runner]
# Runner configuration for better performance
magicEnabled = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"