[server]
# Server configuration for cloud deployment
headless = true
port = 10000
address = "0.0.0.0"
maxUploadSize = 10  # 10MB max upload size
maxMessageSize = 10  # 10MB max message size
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
# Theme configuration for better UX
primaryColor = "#FF6B35"  # About.me orange for primary actions
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# Client configuration
toolbarMode = "minimal"

[runner]
# Runner configuration for better performance
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"